### ISSUE TITLE
Calling [GSDateFuture +allocWithZone:] with incorrect signature.

### ISSUE THREAD

**Issue by 2xsaiko** [gnustep/tools-make#49] opened 2024-12-17 23:08 UTC
Getting this warning from a lot of GNUstep programs (even gopen) on startup.

> `Calling [GSDateFuture +allocWithZone:] with incorrect signature.  Method has @24@0:8^{_NSZone=^?^?^?^?^?^?^?Q@^{_NSZone}}16 (@24@0:8^{_NSZone=^?^?^?^?^?^?^?Q@^{_NSZone}}16), selector has @24@0:8^{_NSZone=}16`

This is with Gentoo's GNUstep packages, clang compiler, libc++, libobjc2. I believe this is some linking issue, since I'm also having other linking related errors (e.g. https://bugs.gentoo.org/946603). No idea though.

What to do here?

**Comment by triplef** [comment] 2024-12-18 09:18
Duplicate of this runtime issue: https://github.com/gnustep/libobjc2/issues/297.

**Closed by triplef** 2024-12-18 09:18 UTC
